FROM python:3.8-slim

WORKDIR /app
COPY mail_service.py .
COPY requirements_service.txt /tmp/requirements_service.txt
RUN pip install --no-cache-dir -r /tmp/requirements_service.txt
EXPOSE 8082
CMD ["uvicorn", "mail_service:app", "--reload", "--host", "0.0.0.0", "--port", "8082"]


